package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;

/* compiled from: com.android.billingclient:billing@@3.0.0 */
public final class zzak {
    public static final BillingResult zza;
    public static final BillingResult zzb;
    public static final BillingResult zzc;
    public static final BillingResult zzd;
    public static final BillingResult zze;
    public static final BillingResult zzf;
    public static final BillingResult zzg;
    public static final BillingResult zzh;
    public static final BillingResult zzk;
    public static final BillingResult zzl;
    public static final BillingResult zzn;
    public static final BillingResult zzo;
    public static final BillingResult zzp;
    public static final BillingResult zzq;
    public static final BillingResult zzr;

    static {
        BillingResult.Builder newBuilder = BillingResult.newBuilder();
        newBuilder.zza = 3;
        newBuilder.zzb = "Google Play In-app Billing API version is less than 3";
        zza = newBuilder.build();
        BillingResult.Builder newBuilder2 = BillingResult.newBuilder();
        newBuilder2.zza = 3;
        newBuilder2.zzb = "Google Play In-app Billing API version is less than 9";
        zzb = newBuilder2.build();
        BillingResult.Builder newBuilder3 = BillingResult.newBuilder();
        newBuilder3.zza = 3;
        newBuilder3.zzb = "Billing service unavailable on device.";
        zzc = newBuilder3.build();
        BillingResult.Builder newBuilder4 = BillingResult.newBuilder();
        newBuilder4.zza = 5;
        newBuilder4.zzb = "Client is already in the process of connecting to billing service.";
        zzd = newBuilder4.build();
        BillingResult.Builder newBuilder5 = BillingResult.newBuilder();
        newBuilder5.zza = 3;
        newBuilder5.zzb = "Play Store version installed does not support cross selling products.";
        zze = newBuilder5.build();
        BillingResult.Builder newBuilder6 = BillingResult.newBuilder();
        newBuilder6.zza = 5;
        newBuilder6.zzb = "The list of SKUs can't be empty.";
        zzf = newBuilder6.build();
        BillingResult.Builder newBuilder7 = BillingResult.newBuilder();
        newBuilder7.zza = 5;
        newBuilder7.zzb = "SKU type can't be empty.";
        zzg = newBuilder7.build();
        BillingResult.Builder newBuilder8 = BillingResult.newBuilder();
        newBuilder8.zza = -2;
        newBuilder8.zzb = "Client does not support extra params.";
        zzh = newBuilder8.build();
        BillingResult.Builder newBuilder9 = BillingResult.newBuilder();
        newBuilder9.zza = -2;
        newBuilder9.zzb = "Client does not support the feature.";
        newBuilder9.build();
        BillingResult.Builder newBuilder10 = BillingResult.newBuilder();
        newBuilder10.zza = -2;
        newBuilder10.zzb = "Client does not support get purchase history.";
        newBuilder10.build();
        BillingResult.Builder newBuilder11 = BillingResult.newBuilder();
        newBuilder11.zza = 5;
        newBuilder11.zzb = "Invalid purchase token.";
        zzk = newBuilder11.build();
        BillingResult.Builder newBuilder12 = BillingResult.newBuilder();
        newBuilder12.zza = 6;
        newBuilder12.zzb = "An internal error occurred.";
        zzl = newBuilder12.build();
        BillingResult.Builder newBuilder13 = BillingResult.newBuilder();
        newBuilder13.zza = 4;
        newBuilder13.zzb = "Item is unavailable for purchase.";
        newBuilder13.build();
        BillingResult.Builder newBuilder14 = BillingResult.newBuilder();
        newBuilder14.zza = 5;
        newBuilder14.zzb = "SKU can't be null.";
        newBuilder14.build();
        BillingResult.Builder newBuilder15 = BillingResult.newBuilder();
        newBuilder15.zza = 5;
        newBuilder15.zzb = "SKU type can't be null.";
        newBuilder15.build();
        BillingResult.Builder newBuilder16 = BillingResult.newBuilder();
        newBuilder16.zza = 0;
        zzn = newBuilder16.build();
        BillingResult.Builder newBuilder17 = BillingResult.newBuilder();
        newBuilder17.zza = -1;
        newBuilder17.zzb = "Service connection is disconnected.";
        zzo = newBuilder17.build();
        BillingResult.Builder newBuilder18 = BillingResult.newBuilder();
        newBuilder18.zza = -3;
        newBuilder18.zzb = "Timeout communicating with service.";
        zzp = newBuilder18.build();
        BillingResult.Builder newBuilder19 = BillingResult.newBuilder();
        newBuilder19.zza = -2;
        newBuilder19.zzb = "Client doesn't support subscriptions.";
        zzq = newBuilder19.build();
        BillingResult.Builder newBuilder20 = BillingResult.newBuilder();
        newBuilder20.zza = -2;
        newBuilder20.zzb = "Client doesn't support subscriptions update.";
        zzr = newBuilder20.build();
        BillingResult.Builder newBuilder21 = BillingResult.newBuilder();
        newBuilder21.zza = 5;
        newBuilder21.zzb = "Unknown feature";
        newBuilder21.build();
    }
}
